version: 2.1



jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation create-stack --stack-name project2-2021-Network --template-body file://network.yml --parameters file://network-parameters.json
      - run: return 1


workflows:
  my_workflow:
    jobs:
      - create_infrastructure